name: Example — CI (calls reusable)

on: { workflow_dispatch: {} }

jobs:
  ci:
    uses: zacharymplace/gha-templates/.github/workflows/reusable-validate.yml@main
    with:
      os: '["ubuntu-latest","windows-latest"]'
      python-versions: '["3.11","3.12"]'
      run-pre-commit: true
      run-coverage: true
      test-command: 'pytest -q --disable-warnings'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
