name: reusable-lint

on:
  workflow_call:
    inputs:
      python-versions:
        description: "JSON array of Python versions"
        required: false
        type: string
        default: '["3.11"]'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(inputs.python-versions) }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements-dev.txt', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Install dev deps (best-effort)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

      # Optional tests: run only if repo has tests/ AND pytest available (or install it)
      - name: Run pytest (optional)
        if: ${{ hashFiles('tests/**') != '' }}
        run: |
          python -m pip install pytest || true
          pytest -q
