name: Reusable — Lint

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.11"
      run-black:
        type: boolean
        default: true
      run-doctoc:
        type: boolean
        default: true
      skip-hooks:
        type: string
        default: ""   # extra hooks to SKIP, e.g. "ruff"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use pip cache only if a deps file exists
      - name: Set up Python (cached)
        if: ${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') != '' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip
          cache-dependency-path: |
            **/requirements*.txt
            **/pyproject.toml

      - name: Set up Python (no cache)
        if: ${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') == '' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache pre-commit envs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: ${{ runner.os }}-precommit-

      - name: Install tooling
        run: |
          python -m pip install -U pip
          python -m pip install pre-commit black

      - name: (Optional) Format with black
        if: ${{ inputs.run-black }}
        run: black .

      - name: (Optional) Update README TOC (doctoc)
        if: ${{ inputs.run-doctoc }}
        run: pre-commit run doctoc --all-files || true

      - name: Build SKIP list for pre-commit
        id: build-skip
        run: |
          SKIP=""
          if [ "${{ inputs.run-black }}" = "true" ]; then SKIP="${SKIP}black,"; fi
          if [ "${{ inputs.run-doctoc }}" = "true" ]; then SKIP="${SKIP}doctoc,"; fi
          if [ -n "${{ inputs.skip-hooks }}" ]; then SKIP="${SKIP}${{ inputs.skip-hooks }},"; fi
          SKIP="${SKIP%%,}"
          echo "skip=$SKIP" >> $GITHUB_OUTPUT

      - name: Lint (pre-commit)
        run: pre-commit run --all-files
        env:
          SKIP: ${{ steps.build-skip.outputs.skip }}
